### ISSUE TITLE
Missing: Gina Häußge

### ISSUE THREAD

**Issue by smurfix** [kemitchell/reference.kemitchell.com#1]
in top-donations-developers.md. She has 1,638 patrons and makes $6,108 per month, as of 2019-09-08.

I tried to create a pull request for this info but the titles for the $$$ columns are confusing. What does "amount" and "mean" mean?

**Comment by kemitchell** [comment]
@smurfix thank you! I will add a line for her shortly.

**Comment by kemitchell** [comment]
@smurfix do you happen to know why Gina receives so many relatively small contributions per month?

**Comment by smurfix** [comment]
Other than a wild guess of "a whole lot of people use Octoprint and already spend a lot of money on that hobby, *and* she provides real value with that program, so a couple more bucks won't hurt, so they feel assed enough to support her", no.

You might simply ask @foosel. ;-)

**Comment by foosel** [comment]
I have no different idea to be honest, but I'm obviously glad it works out.

**Comment by kemitchell** [comment]
@foosel I'm glad for you! Thanks.
